name = "grief_reminders_api"
version = "0.0.1-alpha"

description = "The backend API for the Grief-Reminder project."
# licences = [""] # Who knows?!
repository = { type = "github", user = "EyalRo", repo = "Grief-Reminders-API" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 0.15.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
mist = ">= 1.2.0 and < 2.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
